### ISSUE TITLE
求求了

### ISSUE THREAD

**Issue by JokerTrikcy** [xiby/LECMS#1]
请问您这个项目的py版本是多少。。

**Comment by xiby** [comment]
当时是基于python 3.5开发的，一个课设作业

**Comment by JokerTrikcy** [comment]
> 当时是基于python 3.5开发的，一个课设作业
谢谢大佬 我最近自己也在看django的文档 能加个秋秋好友偶尔交流一下吗

**Comment by xiby** [comment]
可以的，我的QQ：905678638
